export const commands = [
    '!abm',
    '!chatchnl default',
    '!bkup',
    '!cvm',
    '!eggs',
    '!news',
    '!prefix !',
    '!restore',
    '!slowmode 1',
    '!devmode',
    '!eval 1 + 1',
    '!gb 252525252252525252',
    '!gb 252525252252525252',
    '!ub 252525252252525252',
    '!ub 252525252252525252',
    '!abilities',
    '!ep flash 1x1',
    '!nxeps',
    '!op flash',
    '!quote',
    '!soundtracks',
    '!sp flash e1',
    '!subs',
    '!subs flash 1x1',
    '!suit flash',
    '!template',
    '!wiki Barry Allen',
    '!add',
    '!credits',
    '!docs',
    '!donate',
    '!flags',
    '!help',
    '!joke',
    '!jpk',
    '!invite',
    '!mentions',
    '!tr hablo ingles',
    '!trmode',
    '!website',
    '!emojis',
    '!github',
    '!guild',
    '!host',
    '!perms',
    '!ping',
    '!shards',
    '!stats',
    '!uptime',
    '!at iceblast @Anders',
    '!chat hi',
    '!cm a,b',
    '!cuddle @Anders',
    '!show',
    '!lb',
    '!meme',
    '!timeline',
    '!wells',
    '!content',
    '!selfbots',
    '!sources',
    '!tos',
    '!underage',
    '!spoilers',
    '!leaks'
];