export const commands = [
    '!abm',
    '!chatchnl default',
    '!backup',
    '!cvm',
    '!eggs',
    '!news',
    '!prefix !',
    '!restore',
    '!slowmode 1',
    '!devmode',
    '!eval 1 + 1',
    '!gb 252525252252525252',
    '!gb 252525252252525252',
    '!ub 252525252252525252',
    '!ub 252525252252525252',
    '!abilities',
    '!ep flash 1x1',
    '!nxeps',
    '!opening flash',
    '!quote',
    '!soundtracks',
    '!sp flash e1',
    '!subs',
    '!subs flash 1x1',
    '!!suit flash',
    '!template',
    '!wiki Barry Allen',
    '!add',
    '!alias nxeps',
    '!contact',
    '!credits',
    '!djs message',
    '!docs',
    '!donate',
    '!flags',
    '!help',
    '!issues',
    '!joke',
    '!jpk',
    //'!mdn array',
    '!invite',
    '!mentions',
    '!search gues',
    '!tr hablo ingles',
    '!trmode',
    '!website',
    '!emojis',
    '!github',
    '!guild',
    '!host',
    '!guilds',
    '!perms',
    '!ping',
    '!shards',
    '!stats',
    '!status',
    '!uptime',
    '!at iceblast @Anders',
    '!chat hi',
    '!plot',
    '!cm a,b',
    '!cuddle @Anders',
    '!show',
    '!leaderboard',
    '!meme',
    '!timeline',
    '!wells',
    '!content',
    '!selfbots',
    '!sources',
    '!tos',
    '!underage',
    '!spoilers',
    '!leaks'
];